;;; Compiled snippets and support files for `python-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'python-mode
                     '(("while" "while ${condition}:\n    $0" "while ... : ..." nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/while" nil nil)
                       ("utf8" " -*- coding: utf-8 -*-\n" "utf8" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/utf8" nil nil)
                       ("propsg" "def _set_${1:foo}(self, value):\n    self._$1 = value\n\ndef _get_$1(self):\n    return self._$1\n\n$1 = property(_get_$1, _set_$1)\n\n$0" "_get_foo ... _set_foo ... foo=property(...)" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/propsg" nil nil)
                       ("propg" "def _get_${1:foo} (self):\n    return self._$1\n\n$1 = property(_get_$1)\n\n$0" "_get_foo ... foo=property(...)" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/propg" nil nil)
                       ("prop" "def ${1:foo}():\n   doc = \"\"\"${2:Doc string}\"\"\"\n   def fget(self):\n       return self._$1\n   def fset(self, value):\n       self._$1 = value\n   def fdel(self):\n       del self._$1\n   return locals()\n$1 = property(**$1())\n\n$0" "prop" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/prop" nil nil)
                       ("ifmain" "if __name__ == '__main__':\n    $0" "if __name__ == '__main__': ..." nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/ifmain" nil nil)
                       ("for" "for ${var} in ${collection}:\n    $0" "for ... in ... : ..." nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/for" nil nil)
                       ("defm" "def ${1:name}(self, $2):\n    \"\"\"$3\n    ${2:$\n    (let* ((indent\n            (concat \"\\n\" (make-string (current-column) 32)))\n           (args\n            (mapconcat\n             '(lambda (x)\n                (if (not (string= (nth 0 x) \"\"))\n                    (concat \"- \" (char-to-string 96) (nth 0 x)\n                            (char-to-string 96) \":\")))\n             (mapcar\n              '(lambda (x)\n                 (mapcar\n                  '(lambda (x)\n                     (replace-regexp-in-string \"[[:blank:]]*$\" \"\"\n                      (replace-regexp-in-string \"^[[:blank:]]*\" \"\" x)))\n                  x))\n              (mapcar '(lambda (x) (split-string x \"=\"))\n                      (split-string yas-text \",\")))\n             indent)))\n      (if (string= args \"\")\n          (make-string 3 34)\n        (mapconcat\n         'identity\n         (list \"\" \"Arguments:\" args (make-string 3 34))\n         indent)))\n    }\n    $0\n" "defm" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/defm" nil nil)
                       ("def" "def ${1:name}($2):\n    \"\"\"$3\n    ${2:$\n      (let* \n        ((indent\n            (concat \"\\n\" (make-string (current-column) 32)))\n           (args\n            (mapconcat\n             '(lambda (x)\n                (if (not (string= (nth 0 x) \"\"))\n                    (concat \"- \" (char-to-string 96) (nth 0 x)\n                            (char-to-string 96) \":\")))\n             (mapcar\n              '(lambda (x)\n                 (mapcar\n                  '(lambda (x)\n                     (replace-regexp-in-string \"[[:blank:]]*$\" \"\"\n                      (replace-regexp-in-string \"^[[:blank:]]*\" \"\" x)))\n                  x))\n              (mapcar '(lambda (x) (split-string x \"=\"))\n                      (split-string yas-text \",\")))\n             indent)))\n      (if (string= args \"\")\n          (make-string 3 34)\n        (mapconcat\n         'identity\n         (list \"\" \"Arguments:\" args (make-string 3 34))\n         indent)))\n    }\n    $0\n" "def" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/def" nil nil)
                       ("class" "class ${1:ClassName}(${2:object}):\n	\"\"\"$3\n	\"\"\"\n\n	def __init__(self, $4):\n		\"\"\"$5\n		${4:$\n		(let* ((indent\n				(concat \"\\n\" (make-string (current-column) 32)))\n			   (args\n				(mapconcat\n				 '(lambda (x)\n					(if (not (string= (nth 0 x) \"\"))\n						(concat \"- \" (char-to-string 96) (nth 0 x)\n								(char-to-string 96) \":\")))\n				 (mapcar\n				  '(lambda (x)\n					 (mapcar\n					  (lambda (x)\n						(replace-regexp-in-string \"[[:blank:]]*$\" \"\"\n						 (replace-regexp-in-string \"^[[:blank:]]*\" \"\" x))) x))\n				  (mapcar '(lambda (x) (split-string x \"=\"))\n						  (split-string yas-text \",\")))\n				 indent)))\n		  (if (string= args \"\")\n			  (make-string 3 34)\n			(mapconcat\n			 'identity\n			 (list \"\" \"Arguments:\" args (make-string 3 34))\n			 indent)))\n		}\n		${4:$\n		(mapconcat\n		 '(lambda (x)\n			(if (not (string= (nth 0 x) \"\"))\n				(concat \"self._\" (nth 0 x) \" = \" (nth 0 x))))\n		 (mapcar\n		  '(lambda (x)\n			 (mapcar\n			  '(lambda (x)\n				 (replace-regexp-in-string \"[[:blank:]]*$\" \"\"\n				  (replace-regexp-in-string \"^[[:blank:]]*\" \"\" x)))\n			  x))\n		  (mapcar '(lambda (x) (split-string x \"=\"))\n				  (split-string yas-text \",\")))\n		 (concat \"\\n\" (make-string (current-column) 32)))\n		}\n		$0\n" "class" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/class" nil nil)
                       ("__" "__${init}__" "__...__" nil nil nil "/home/jim/.spacemacs.d/my-yas/python-mode/__" nil nil)))


;;; Do not edit! File generated at Sat Jun 29 15:48:12 2019
